- name: Add remmina apt repo
  apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next

- name: Add signal key
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present
    
- name: Add signal repo
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: Install apt packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - snapd
    - htop
    - libreoffice
    - tmux
    - icedtea-netx
    - mesa-utils
    - remmina 
    - remmina-plugin-rdp 
    - remmina-plugin-secret 
    - remmina-plugin-spice
    - thunderbird
    - tlp
    - signal-desktop
    - steam-installer
    - freerdp-x11

- name: Make sure snapd is running
  systemd:
    state: started
    name: snapd
