- name: Add chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add chome repo
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present

- name: Install apt packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - snapd
    - htop
    - libreoffice
    - tmux
    - icedtea-netx
    - mesa-utils
    - tlp
    - steam-installer
    - evolution
    - evolution-ews
    - google-chrome-stable
    - gnome-tweak-tool
    - gnome-multi-writer
    - youtube-dl
    ##- cifs-utils
    ##- gvfs

- name: Install snap packages
  snap:
    name:
      - signal-desktop
      - remmina
      - keepassxc
      - inkscape
      
- name: Install code with option --classic
  snap:
    classic: yes
    name:
      - code
      - skype

- name: Make sure snapd is running
  systemd:
    state: started
    name: snapd
