- name: Add remmina apt repo
  apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next

- name: Install apt packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - snapd
    - htop
    - tmux
    - icedtea-netx
    - mesa-utils
    - remmina 
    - remmina-plugin-rdp 
    - remmina-plugin-secret 
    - remmina-plugin-spice
    - thunderbird

- name: Make sure snapd is running
  systemd:
    state: started
    name: snapd
