- name: Install apt packages
  apt: name={{item}}
  with_items:
    - snapd
    - htop
    - tmux
    - icedtea-netx

- name: Make sure snapd is running
  systemd:
    state: started
    name: snapd

- name: Install snap packages
  snap:
    name:
      - remmina
