- name: Install apt packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - snapd
    - htop
    - tmux
    - icedtea-netx


- name: Make sure snapd is running
  systemd:
    state: started
    name: snapd

- name: Install snap packages
  snap:
    name:
      - remmina
