- name: Add remmina apt repo
  apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next



- name: Add chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add chome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install apt packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - snapd
    - htop
    - libreoffice
    - tmux
    - icedtea-netx
    - mesa-utils
    #- remmina 
    #- remmina-plugin-rdp 
    #- remmina-plugin-secret 
    #- remmina-plugin-spice
    - thunderbird
    - tlp
    - steam-installer
    - freerdp-x11
    - google-chrome-stable
    - keepassxc
    - inkscape
    - cifs-utils
    - gvfs

- name: Install snap packages
  snap:
    name:
      - signal-desktop
      - remmina
      
- name: Install code packages with option --classic
  snap:
    name: code
    classic: yes

- name: Make sure snapd is running
  systemd:
    state: started
    name: snapd
